# Docker Compose Template - Basic
# Author: QZCL Maintainer <maintainer@qzconsultancy.com>
# Git Repo: https://github.com/qzcl-maintainer/docker-compose-templates.git
# Created: 10-Sep-2024
# Purpose: To spin up a basic docker container.  In this example we will spin up an nginx instance called "app".
#
# References:
#   1. https://docs.docker.com/reference/compose-file/version-and-name/

# Specify the Version of your compose file, i.e. v0.1
version: "1"
name: app

services:
  # Specify the name of your service
  app:
    # Name the container explicitly
    container_name: app
    # Set a custom hostname
    hostname: app-nginx-prod
    # Use the official Nginx image
    image: nginx:1.27.0
    # Map ports from the host to the container
    ports:
      - "80:80"
    # Define mounted volumes (for persistent data storage or custom configuration)
    volumes:
      - app-data:/usr/share/nginx/html  # Adjusted to serve HTML files from the host
    # Assign the container to a custom network
    networks:
      - app-net
    # Automatically restart the container if it stops or crashes
    restart: unless-stopped

# Define persistent named volumes
volumes:
  app-data:

# Define custom networks for inter-service communication
networks:
  app-net:

# Check the config file by running `docker compose -f basic-compose.yml config`
# End of Compose File

